/**
 * Generated by scripts/install-plugin.sh. Do not edit.
 *
 * A short hash of the plugin sources at install time. `bridge.js` sends it in
 * `hello` so a caller can compare it against the sources on disk and know whether
 * the plugin Photoshop is running is the code that was just written, without reading
 * log text and guessing.
 */
module.exports = { buildId: 'd356632fc106' };
